language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

branches:
  only:
  - master

script:
  - yarn build

notifications:
  email:
    recipients:
      - u201320891@upc.edu.pe
      - u201514642@upc.edu.pe
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: master
